### ISSUE TITLE
Could you tell me how to find room_id easily?

### ISSUE THREAD

**Issue by 1syo** [idobata/hubot-idobata#16]
Thank you for good chat service and I have one question.

When I want to post message to idobata from hubot regularly,
I write script using node-cron moudle like this.

scripts/cron.coffee
```
cronJob = require('cron').CronJob
module.exports = (robot) ->
	new cronJob('0 0 8 * * *', () ->
		robot.send {room: 5586}, "Good morning."
	).start()
```
The 5586 is room_id. I found room_id with debugging hubot-idobata adapter.
I think that I want to find it easily.

Could you tell me how to find room_id easily?
For instance, I will be able to find it on management console, or with calling API.

**Comment by 1syo** [comment]
or, I want to post message with room name like this.

```
cronJob = require('cron').CronJob
module.exports = (robot) ->
	new cronJob('0 0 8 * * *', () ->
		robot.send {room: ‘general’} , "Good morning."
	).start()
```

**Comment by hibariya** [comment]
Thank you for opening this issue.

> Could you tell me how to find room_id easily?

Good question.
Unfortunately, for now, Idobata doesn't have the official way to get room_id. 
I think that we have to announce information officialy for that.

For band-aid solution, let me show how to get room_id easily.

```javascript
// (Visit the room, open brower's console and do this:)
var store = Ember.Application.byName('idobata').__container__.lookup('service:store');
var room = store.peekAll('room').find(function(room) {
  return (room.get('organization.slug') === 'THE_ORGANIZATION_SLUG' && room.get('name') === 'THE_ROOM_NAME'); });
room.get('id') // returns room_id
```

Please note that it is unofficial way and may be changed.

**Comment by 1syo** [comment]
Thank you for your help!! :smile_cat:

**Comment by 1syo** [comment]
I was able to get room_id.
Thank you. :smile:

**Comment by hibariya** [comment]
Yay, good for you :smiley:

**Comment by hibariya** [comment]
> For instance, I will be able to find it on management console, or with calling API.

Sounds good. I have added a pane about room_id into room-settings page right now.

![selection_331](https://cloud.githubusercontent.com/assets/43346/10630479/b4303976-7811-11e5-9ef0-ce6241bb1000.png)

**Comment by 1syo** [comment]
LGTM :+1::sparkles::ok_woman::suge-iine::gift_heart::tada::bulb:

**Comment by hibariya** [comment]
:blush: :dancer: :sparkles:

**Comment by hibariya** [comment]
This is done, so I'm closing :)
